### ISSUE TITLE
Use abidiff on dynamic libraries

### ISSUE THREAD

**Issue by thesamesam** [ionenwks/iwdevtools#1]
I was wondering about this anyway but I suppose it’s slightly less of a leap now that https://github.com/ionenwks/iwdevtools/commit/68ab9fba31d0db0b42d4f9244f0420a7687c20f5 landed.

libabigail provides abidiff which makes it a lot easier to spot unexpected breakage.

**Comment by ionenwks** [comment]
Good idea, and it should be fairly trivial by using the image to compare (which I could've done for the others too, may simplify these to just preinst).

Do you think it'd be enough to run this only when the soname didn't change? (i.e. to spot upstream doing bad things) Be trivial to find what to compare with given same filenames and upstreams sometime use odd version like libname-ver.so instead of .so.ver which I'd need to figure out.
