### ISSUE TITLE
About pcsx2, sorry I couldn't find an email or another way to contact you

### ISSUE THREAD

**Issue by kenshen112** [ionenwks/iwdevtools#14]
I'm the maintainer of the pcsx2-git package for the AUR. With the recent ... _work_ Stenz has been doing for pcsx2 I've been maintaining patches to reapply package mode and any other change I've thought weren't the best. https://aur.archlinux.org/cgit/aur.git/tree/0001-Fix-resources-Fix-CMake.patch?h=pcsx2-git If you want to keep going with the latest nightly I'll be keeping that up to date with any changes he makes

**Comment by ionenwks** [comment]
Thanks, but felt it wasn't worth trying to keep package mode given doing a manual install isn't /too/ involved (the whole thing just feels kind of silly).

Notable bits from the ebuilds are first to set the AppRoot to /usr/share/pcsx2 (could be a patch but sed is convenient for us given EPREFIX is non-static):
```
    sed -e "/EmuFolders::AppRoot =/s|=.*|= \"${EPREFIX}/usr/share/${PN}\";|" \
        -i pcsx2/Frontend/CommonHost.cpp || die
```
An alternate route could be doing like alpine and use a wrapper instead, more solid although have to install things in weird locations.

And the install:
```
    newbin "${BUILD_DIR}"/pcsx2-qt/pcsx2-qt ${PN}

    insinto /usr/share/${PN}
    doins -r "${BUILD_DIR}"/pcsx2-qt/resources

    dodoc README.md bin/docs/{Debugger.pdf,GameIndex.pdf,PCSX2_FAQ.pdf,debugger.txt}
    newman bin/docs/PCSX2.1 ${PN}.1

    newicon bin/resources/icons/AppIconLarge.png ${PN}.png
    make_desktop_entry ${PN} ${PN^^}
```
Suppose could switch to the .desktop from `.github/workflows/scripts/linux/pcsx2-qt.desktop` rather than our make_desktop_entry but well, leaving it alone for now. May do some cleanups later when things stop changing.

https://gitweb.gentoo.org/repo/gentoo.git/tree/games-emulation/pcsx2/pcsx2-9999.ebuild
