### ISSUE TITLE
misleading suggestions

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ionenwks/iwdevtools#3]
The tool is suggesting to depend on `gnat-gpl` and `julia` on almost every package that I'm building

```
>>> Original instance of package unmerged safely.
 * QA: detected possibly incorrect RDEPEND (sys-cluster/sionlib-1.7.7-r3)
 * +dev-lang/gnat-gpl:10
 * +dev-lang/gnat-gpl:9.3.1
 * +dev-lang/julia
```

**Comment by ionenwks** [comment]
For now you can add this to `/etc/iwdevtools/qa-vdb.exclude`
```
dev-lang/gnat-gpl
dev-lang/julia
```

It's because it provides gcc libraries and qa-vdb thinks it's a valid provider (i.e. linked against libgcc_s.so but not in RDEPEND), normally gcc is excluded but it doesn't know about other packages that come with the whole thing, i.e.
```
$ qlist -e gnat-gpl | grep -F libgcc_s.so.1
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.1/32/libgcc_s.so.1
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.1/libgcc_s.so.1
```

Unsure if I want to add a special handler for these libraries, I may just add offending packages to qa-vdb.exclude by default.

**Comment by ionenwks** [comment]
Hm, actually I may do a special exception for libgcc_s.so given there's a few random /opt packages that provide it too and the list will get unnecessarily long.
