### ISSUE TITLE
colored output unintelligible with gnome-terminal's Solarized Dark theme

### ISSUE THREAD

**Issue by xen0n** [ionenwks/iwdevtools#8]
![example of output](https://user-images.githubusercontent.com/1175567/170178351-1fa11ca4-4726-40c5-97b1-e1f06201ec2b.png)

I'm using latest GNOME and gnome-terminal's preset Solarized Dark theme, and it seems a lot of text is rendered with the same foreground and background color :facepalm:

I may be able to fix the problem myself, but can only do so a few days later, so I'm reporting here in case I forget.

**Comment by ionenwks** [comment]
Colors that aren't visible seem more like a theme issue (otherwise what use are they?), but it's possible to configure iwdevtools' colors too. That "missing" color is grey meant to put emphasis on the `:=` instead.

It's not well documented, but if look at `qa-vdb --dumpconfig` there's:
```
# grey,red,green,yellow,blue,magenta,cyan,light*7,white,neutral
#colormap = 90 31 32 33 34 35 36 37 91 92 93 94 95 96 97 0
```
So can uncomment, change 90 to something else (e.g. 0 for terminal's default color), and save the dumped config to `/etc/iwdevtools/qa-vdb.conf` (`~/.config/iwdevtools/qa-vdb.conf` works too but portage won't like in your own HOME).

Can do the same qa-cmp and other tools (see their --help, they all support --dumpconfig).

**Comment by ionenwks** [comment]
Colors remain unchanged, but as mentioned that's essentially a broken theme if basic colors are invisible.

Now installing .conf files by default so it's easier to find how to configure colors though.
